// Generated by gencpp from file my_pkg/Command.msg
// DO NOT EDIT!


#ifndef MY_PKG_MESSAGE_COMMAND_H
#define MY_PKG_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_pkg
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : upper(0)
    , lower(0)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : upper(0)
    , lower(0)  {
  (void)_alloc;
    }



   typedef int8_t _upper_type;
  _upper_type upper;

   typedef int8_t _lower_type;
  _lower_type lower;




  typedef boost::shared_ptr< ::my_pkg::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_pkg::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::my_pkg::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::my_pkg::Command > CommandPtr;
typedef boost::shared_ptr< ::my_pkg::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_pkg::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_pkg::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mypkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mypkg': ['/home/rob/ws0/src/mypkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_pkg::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_pkg::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_pkg::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_pkg::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_pkg::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_pkg::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_pkg::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "715230e61ae49e8eb5988a0e6ed0c923";
  }

  static const char* value(const ::my_pkg::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x715230e61ae49e8eULL;
  static const uint64_t static_value2 = 0xb5988a0e6ed0c923ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_pkg::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_pkg/Command";
  }

  static const char* value(const ::my_pkg::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_pkg::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 upper\n\
int8 lower\n\
";
  }

  static const char* value(const ::my_pkg::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_pkg::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.upper);
      stream.next(m.lower);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_pkg::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_pkg::Command_<ContainerAllocator>& v)
  {
    s << indent << "upper: ";
    Printer<int8_t>::stream(s, indent + "  ", v.upper);
    s << indent << "lower: ";
    Printer<int8_t>::stream(s, indent + "  ", v.lower);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PKG_MESSAGE_COMMAND_H
